### ISSUE TITLE
How to download ./dataset/zju_mocap/CoreView_377CoreView_377/new_params/0.npy

### ISSUE THREAD

**Issue by ChengXinyi0415** [Yifever20002/ToMiE#2]
How to download CoreView_377/new_params/0.npy in the zju_mocap dataset? The data I downloaded from Google Drive does not contain this file.
![A6C92F0488FAE8FD367474DA9FF02E67](https://github.com/user-attachments/assets/6ee05190-706c-4dce-8b9d-06ace8fb37aa)

**Comment by Yifever20002** [comment]
We previously provided incorrect version of ZJU_MoCap dataset (as there are lots of versions :)) . We sincerely apologize for this! The link has now been updated, and you can download the corresponding ZJU data through the latest link.
![微信图片_20241016193731](https://github.com/user-attachments/assets/03bc36fc-1eb8-4d00-9a6d-519d24fa0ab8)

**Comment by ChengXinyi0415** [comment]
problem is solved, thanks!
